services:
  db:
    image: danii04/mi_cine_repaso_examen:v1
    container_name: contenedorMiCineRepasoExamen
    ports:
      - "3306:3306"

  php:
    image: danii04/mi_app_cine_repaso_examen:v1
    container_name: contenedorMiAppRepasoExamen
    ports:
      - "8080:80"
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: contenedorPhpMyAdminRepasoExamen
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: contrasenyaRoot
    ports:
      - "8081:80"
    depends_on:
      - db
